// /controllers/v2/system/errorHandler/errorHandler.ts

/**
 * @module errorHandler
 * @description This is the centralized error handler of the Mcitys API.
 * It delivers standard responses and logs every error.
 * 
 * @param {string | Error} error // The error message or an Error object
 * @param {number | undefined} code
 * If set to TRUE the original message sent by the caller module is transmitted uncrypted to the client.
 * @param {boolean | undefined} isMessagePublic 
 * @returns {errorObject: {message: string, code: number}}
 */

const environment = require('../environment'); // À ajuster selon le chemin réel
const httpCodes = require('./httpErrorcodes'); // À ajuster selon le chemin réel

import { HttpError } from "./httpError"; 

/** Interfaces */
interface IErrorObject {
    message: string;
    statusCode: number;
    isMessagePublic?: boolean;
}

export function handle(error: string | Error | IErrorObject, code?: number, isMessagePublic?: boolean) {

    // Determine the type of error
    const isStandardError = error instanceof Error;
    const isHttpError = error instanceof HttpError;
    const isErrorConfigObject = !isStandardError && typeof error === 'object' && error !== null;

    // Handling message
    const msg = isStandardError || isErrorConfigObject
        ? error.message // Prend le message de l'objet Error ou IErrorObject
        : String(error); // Sinon, convertit la string passée

    // Generating stack trace
    const stackToLog = isStandardError ? error.stack : (new Error(msg)).stack;
    
    // Determine environment
    const isDev = environment.getEnvironment.mode === 'dev';
    
    // Determine if message is public:
    // 1. Retrieving isMessagePublic from HttpError if applicable
    // 2. Otherwise, use the parameter isMessagePublic
    const isPublic = isHttpError ? (error as HttpError).isMessagePublic : isMessagePublic || false;
    
    console.log(stackToLog);
    
    /** DETERMINE ERROR CODE */
    let errCode: number;

    // Does the error object have a status ?
    const isAnHttpCompatibleError = (
        typeof error === 'object' && 
        error !== null && 
        ('status' in error || 'statusCode' in error)
    );

    // Prioritizing the provided error code
    if (code && typeof code === 'number' && code >= 100 && code < 600) {
        errCode = code;

    // If the error param is an instance of HttpError, get the code from the error object
    } else if (isHttpError && (error as HttpError).statusCode) {
        errCode = (error as HttpError).statusCode;

    // If the error is generated by Express / create-error
    } else if (isAnHttpCompatibleError) {
        const expressError = error as { status?: number, statusCode?: number };
        // Getting the .status (for the 404 case), otherwise the .statusCode, or finaly the 500
        errCode = expressError.status || expressError.statusCode || 500;
    }

    // For simple JS errors without any status.
    else {
        errCode = code || 500;
    }

    /** GENERATING RESPONSE OBJECT */

    if (isPublic) {
        return { message: msg, statusCode: errCode };
    } else {
        if (isDev) {
            return { message: msg, statusCode: errCode };
        } else {
            return {
                message: httpCodes.httpCodes[errCode] || httpCodes.httpCodes[500],
                statusCode: errCode
            };
        }
    }
}